name: tests

on: [push]

jobs:
  run_tests:
    runs-on: macOS-latest
    strategy:
      matrix:
        include:
          - xcode: "14.0.1"
            ios: "16.0"
    name: test iOS (${{ matrix.ios }})
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_$.app && /usr/bin/xcodebuild -version
    - name: Run unit tests
      run: xcodebuild test -scheme Tegami -project Tegami.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 14,OS=$' | xcpretty && exit ${PIPESTATUS[0]}