on: pull_request

name: CI

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Testing
        run: |
          xcodebuild \
          test \
          -project Tegami.xcodeproj \
          -scheme Tegami \
          -destination 'platform=iOS Simulator,name=iPhone 14'
        env:
           destination: ${{ matrix.destination }}
           CODECOV_TOKEN: ${{ secrets.codecov_token }}
